DROP TABLE ADRESY CASCADE CONSTRAINTS;
DROP TABLE OSOBY CASCADE CONSTRAINTS;
DROP TABLE BIURO_AGENCJI CASCADE CONSTRAINTS;
DROP TABLE ROLE CASCADE CONSTRAINTS;
DROP TABLE PRACOWNICY_AGENCJI CASCADE CONSTRAINTS;
DROP TABLE USLUGI CASCADE CONSTRAINTS;
DROP TABLE TYPY_NIERUCHOMOSCI CASCADE CONSTRAINTS;
DROP TABLE WLASCICIEL_NIERUCHOMOSCI CASCADE CONSTRAINTS;
DROP TABLE DANE_NIERUCHOMOSCI CASCADE CONSTRAINTS;
DROP TABLE PLATNOSCI CASCADE CONSTRAINTS;
DROP TABLE KLIENT_AGENCJI CASCADE CONSTRAINTS;
DROP TABLE TRANSAKCJE CASCADE CONSTRAINTS;

DROP VIEW WIDOK_1;
DROP VIEW WIDOK_2;
DROP VIEW WIDOK_3;
DROP VIEW WIDOK_4;
DROP VIEW WIDOK_5;
DROP VIEW WIDOK_6;

DROP FUNCTION KURSOR_1;
DROP PROCEDURE KURSOR_2;
DROP PROCEDURE KURSOR_3;
DROP PROCEDURE KURSOR_4;
DROP PROCEDURE Kopiowanie;

DROP TRIGGER WYZWALACZ_1;
DROP TRIGGER WYZWALACZ_2;
DROP TRIGGER WYZWALACZ_3;